### ISSUE TITLE
Change StorageSelectDialog to use support fragment dialog

### ISSUE THREAD

**Issue by EladKeyshawn** [mhutti1/android-storage-devices#5]
There are more fragments not using the support one, and for me with the onboarding I'm trying to initiate the library fragment which is dependent on StorageSelectDialog and its needed to use the support fragment.

**Comment by mhutti1** [comment]
@EladKeyshawn Already done I am working on the fragment change here https://github.com/kiwix/kiwix-android/tree/mhutti1/fragments
